################################################################
## Z-Wave / Device Config
################################################################

################################################
## Door/Window Sensor
################################################

sensor.michaels_closet_door_contact_access_control:
  ignored: true

sensor.michaels_closet_door_contact_alarm_level:
  ignored: true

sensor.michaels_closet_door_contact_alarm_type:
  ignored: true

sensor.michaels_closet_door_contact_sourcenodeid:
  ignored: true

sensor.julias_closet_door_contact_access_control:
  ignored: true

sensor.julias_closet_door_contact_alarm_level:
  ignored: true

sensor.julias_closet_door_contact_alarm_type:
  ignored: true

sensor.julias_closet_door_contact_sourcenodeid:
  ignored: true

sensor.guest_bedroom_storage_door_contact_access_control:
  ignored: true

sensor.guest_bedroom_storage_door_contact_alarm_level:
  ignored: true

sensor.guest_bedroom_storage_door_contact_alarm_type:
  ignored: true

sensor.guest_bedroom_storage_door_contact_sourcenodeid:
  ignored: true

sensor.guest_bedroom_closet_door_contact_access_control:
  ignored: true

sensor.guest_bedroom_closet_door_contact_alarm_level:
  ignored: true

sensor.guest_bedroom_closet_door_contact_alarm_type:
  ignored: true

sensor.guest_bedroom_closet_door_contact_burglar:
  ignored: true

sensor.guest_bedroom_closet_door_contact_general:
  ignored: true

sensor.guest_bedroom_closet_door_contact_sourcenodeid:
  ignored: true

################################################
## Flood Sensor
################################################

binary_sensor.laundry_room_flood_sensor:
  ignored: true

sensor.laundry_room_flood_sensor_alarm_level:
  ignored: true

sensor.laundry_room_flood_sensor_alarm_type:
  ignored: true

sensor.laundry_room_flood_sensor_2:
  ignored: true

sensor.laundry_room_flood_sensor_general:
  ignored: true

sensor.laundry_room_flood_sensor_sourcenodeid:
  ignored: true

################################################
## Garage Door
################################################

sensor.garage_door_opener_sourcenodeid:
  ignored: true

sensor.garage_door_opener_access_control:
  ignored: true

sensor.garage_door_opener_alarm_level:
  ignored: true

sensor.garage_door_opener_alarm_type:
  ignored: true

sensor.garage_door_opener_burglar:
  ignored: true

################################################
## Lights
################################################

light.living_room_floor_lamp_2:
  ignored: true

sensor.living_room_floor_lamp_current:
  ignored: false

sensor.living_room_floor_lamp_energy:
  ignored: false

sensor.living_room_floor_lamp_power:
  ignored: false

sensor.living_room_floor_lamp_voltage:
  ignored: false

sensor.living_room_floor_lamp_previous_reading:
  ignored: true

light.living_room_bookshelf_lamp_level_2:
  ignored: true

sensor.living_room_bookshelf_lamp_current:
  ignored: false

sensor.living_room_bookshelf_lamp_energy:
  ignored: false

sensor.living_room_bookshelf_lamp_power:
  ignored: false

sensor.living_room_bookshelf_lamp_voltage:
  ignored: false

sensor.living_room_bookshelf_lamp_previous_reading:
  ignored: true

light.guest_bedroom_closet:
  refresh_value: true
  delay: 3

light.garage_storage:
  refresh_value: true
  delay: 3

light.dungeon:
  refresh_value: true
  delay: 3

################################################
## Multisensor
################################################

sensor.kitchen_motion_sensor_alarm_level:
  ignored: true

sensor.kitchen_motion_sensor_alarm_type:
  ignored: true

sensor.kitchen_motion_sensor_sourcenodeid:
  ignored: true

sensor.master_bedroom_motion_sensor_alarm_level:
  ignored: true

sensor.master_bedroom_motion_sensor_alarm_type:
  ignored: true

sensor.master_bedroom_motion_sensor_sourcenodeid:
  ignored: true

sensor.master_bedroom_motion_sensor_ultraviolet:
  ignored: true

sensor.living_room_motion_sensor_alarm_level:
  ignored: true

sensor.living_room_motion_sensor_alarm_type:
  ignored: true

sensor.living_room_motion_sensor_general:
  ignored: true

sensor.living_room_motion_sensor_sourcenodeid:
  ignored: true

sensor.living_room_motion_sensor_acceleration_x_axis:
  ignored: true

sensor.living_room_motion_sensor_acceleration_y_axis:
  ignored: true

sensor.living_room_motion_sensor_acceleration_z_axis:
  ignored: true

################################################
## Smoke Detectors
################################################

sensor.guest_bedroom_smoke_and_carbon_monoxide_detector_alarm_type:
  ignored: true

sensor.master_bedroom_smoke_and_carbon_monoxide_detector_alarm_type:
  ignored: true

sensor.laundry_room_smoke_and_carbon_monoxide_detector_alarm_type:
  ignored: true

################################################
## Switch
################################################

sensor.basement_task_light_current:
  ignored: false

sensor.basement_task_light_energy:
  ignored: false

sensor.basement_task_light_power:
  ignored: false

sensor.basement_task_light_previous_reading:
  ignored: true

sensor.basement_task_light_voltage:
  ignored: false
